% ==================================================================
% FILE     MGT-MST-images.cls
% MACHINE  all
% INFO     Erstellungsteam: Bilder für Microsoft Word Einsatz
%
% DATE     23.07.2017
% OWNER    Bischofberger
% ==================================================================

\ProvidesClass{MGT-MST-images}
\NeedsTeXFormat{LaTeX2e}

% KOMA
\LoadClass[crop,10pt,tikz]{standalone}

% fonts
\RequirePackage[T1]{fontenc}
\RequirePackage[utf8x]{inputenc}
\RequirePackage[ngerman]{babel}
\RequirePackage{lmodern}

\RequirePackage{mathtools}
\RequirePackage{amssymb}

% units
\RequirePackage{siunitx}
\sisetup{per-mode=symbol}

\RequirePackage{tikzStyle}
